### ISSUE TITLE
Duplicate image folder with scores as prefix

### ISSUE THREAD

**Issue by chrisgoringe** [chrisgoringe/Custom-classifier-training#19]
0.123_name.png

How to deal with negative scores?

**Comment by bmf-info** [comment]
I think we could:
- Separate them into two folders.
- Use the letters "p" and "n."
- Or, place the position in front of them (from the best to worst image) using padding like 0001, 0002, 0003... 0010, etc.

![2023-12-12 15_58_07-Window](https://github.com/chrisgoringe/Custom-classifier-training/assets/149558499/cbb8b1d4-d5a0-4d41-8701-0c16b77ab278)

![2023-12-12 16_00_35-Window](https://github.com/chrisgoringe/Custom-classifier-training/assets/149558499/bcfdc596-cefb-4edb-a170-30d3fb72865e)

**Comment by chrisgoringe** [comment]
done
