### ISSUE TITLE
Export model during training if it get better result than the current best model.

### ISSUE THREAD

**Issue by bmf-info** [chrisgoringe/Custom-classifier-training#26]
As title. It might save us some time since the last model isn't always the best one.

![2023-12-24 17_22_01-Window](https://github.com/chrisgoringe/Custom-classifier-training/assets/149558499/3347b6ba-f889-4ffe-93c7-aebe79a9233a)

**Comment by chrisgoringe** [comment]
in arguments.py, in training_arguments, set:

```python
"save_strategy"                 : "epoch",      (line 109)

"evaluation_strategy"           : "epoch",   (line 114)

"load_best_model_at_end"        : True,    (line 123)
```

and it should do this (according to transformers documentation, I haven't tried!). May also need to add:

```python
"metric_for_best_model" : "eval_loss",
```

to make it use the evaluation set not the training set to define the 'best'.

**Comment by chrisgoringe** [comment]
If using 'epoch' slows it down too much, set those two to 'steps' and set "save_steps" and "eval_steps" to some suitable value (higher means evaluate less frequently).

**Comment by bmf-info** [comment]
The issue was regarding the metasearch so "save_steps" and "eval_steps" may not work since we don't know the number of steps each trial takes. Over 100 trials, I noticed that there are good models that surpass the accuracy level of the current best model but are getting ignored.
The script only compares the last model of each trial with one another.

**Comment by chrisgoringe** [comment]
Made redundant my metaparameter search
